### ISSUE TITLE
Trouble running gui code 

### ISSUE THREAD

**Issue by 1madison24** [OpenEVSE/openevse-gui-v2#48]
Hello,
I am currently running the unmodified code but am receiving this error not allowing me to move forward. I followed the instructions in the read me. Is there a step that I am missing. 

<img width="1428" alt="Screenshot 2023-11-22 at 10 04 08 AM" src="https://github.com/OpenEVSE/openevse-gui-v2/assets/92468456/f00b9e35-ebad-4131-a97c-5716bec0a38a">

**Comment by jeremypoulter** [comment]
Do you have a `.env` file? If not you can find an example https://github.com/OpenEVSE/openevse-gui-v2/blob/master/.env.example copy it and update to your environment

**Comment by 1madison24** [comment]
I added the address of the central system server as well (again this could be wrong) but I get a new error
<img width="1427" alt="Screenshot 2023-11-28 at 8 38 45 AM" src="https://github.com/OpenEVSE/openevse-gui-v2/assets/92468456/84df67a8-8b54-4b8b-9b2b-d3cfd53c37b4">

**Comment by 1madison24** [comment]
Update: My issue is fixed thank you for your help
